project:
  type: book
  output-dir: docs

execute:
  cache: true

book:
  title: Introduction to Data Science
  subtitle: Statistics and Prediction Algorithms Through Case Studies
  reader-mode: true
  page-footer:
    left: |
      Introduction to Data Science was written by Rafael A. Irizarry
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: http://rafalab.dfci.harvard.edu/dsbook-part-2
  repo-url: https://github.com/rafalab/dsbook-part-2
  repo-branch: main
  repo-actions: [source, issue]
  sidebar:
    collapse-level: 1

  chapters:
    - index.qmd

    - intro.qmd

    - part: summaries/intro-summaries.qmd
      chapters:
        - summaries/distributions.qmd
        - summaries/numerical-summaries.qmd
        - summaries/comparing-groups.qmd
        - summaries/reading-summaries.qmd

    - part: prob/intro-to-prob.qmd
      chapters:
        - prob/connecting-data-and-probability.qmd
        - prob/discrete-probability.qmd
        - prob/continuous-probability.qmd
        - prob/random-variables.qmd
        - prob/sampling-models-and-clt.qmd
        - prob/reading-prob.qmd

    - part: inference/intro-inference.qmd
      chapters:
        - inference/parameters-estimates.qmd
        - inference/confidence-intervals.qmd
        - inference/models.qmd
        - inference/bayes.qmd
        - inference/hierarchical-models.qmd
        - inference/hypothesis-testing.qmd
        - inference/bootstrap.qmd
        - inference/reading-inference.qmd
        
    - part: linear-models/intro-to-linear-models.qmd
      chapters:
        - linear-models/regression.qmd
        - linear-models/measurement-error-models.qmd
        - linear-models/treatment-effect-models.qmd
        - linear-models/association-tests.qmd
        - linear-models/association-not-causation.qmd
        - linear-models/multivariable-regression.qmd
        - linear-models/reading-lm.qmd
        
    - part: highdim/intro-highdim.qmd
      chapters:
        - highdim/matrices-in-R.qmd
        - highdim/linear-algebra.qmd
        - highdim/dimension-reduction.qmd
        - highdim/regularization.qmd
        - highdim/latent-factor-models.qmd
        - highdim/reading-highdim.qmd

    - part: ml/intro-ml.qmd
      chapters:
        - ml/notation-and-terminology.qmd
        - ml/evaluation-metrics.qmd
        - ml/conditionals.qmd
        - ml/smoothing.qmd
        - ml/resampling-methods.qmd
        - ml/algorithms.qmd
        - ml/clustering.qmd
        - ml/ml-in-practice.qmd
        - ml/reading-ml.qmd
        
format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true
    author-meta: Rafael A. Irizarry
    callout-appearance: simple
    number-sections: true
    number-depth: 2
  pdf: 
    documentclass: krantz
    classoption: [krantz2,10pt,twoside,onecolumn,final,openright]
    include-in-header: preamble.tex
    header-includes: |
     \usepackage{amssymb}
     \usepackage{amsmath}
     \usepackage{graphicx}
     \usepackage{subfigure}
     \usepackage{makeidx}
     \usepackage{multicol}
    keep-tex: true
    number-sections: true
    number-depth: 2
    code-overflow: wrap

knitr:
  opts_chunk:
    comment: "#>"
    collapse: TRUE
    cache: TRUE
    width: 72
    tidy.opts: list(width.cutoff=72, tidy=TRUE)
    out.width: 70%
    fig.align: 'center'
    fig.width: 6
    fig.height: 3.708  # width * 1 / phi
    fig.show: hold
    R.options:
      digits: 3
      width: 72
      formatR.indent: 2
      dplyr.summarise.inform: FALSE
      dplyr.print_min: 5 
      dplyr.print_max: 5
      ggrepel.max.overlaps: 100

editor: source
