# Linear Models {.unnumbered}

Up to this point, the book has focused mainly on datasets with a single variable. In real data analysis, however, we are often interested in the relationship between two or more variables. In this part of the book, we introduce linear models, a general framework that unifies methods for studying associations among variables, including simple and multivariable regression, treatment effect models, and association tests. We will use several case studies to illustrate these ideas. We will examine whether height is hereditary (@sec-regression), how to build a baseball team on a budget (@sec-multivariable-regression), whether a high-fat diet makes mice heavier (@sec-treatment-effect-models), and whether there is gender bias in research funding in the Netherlands (@sec-association-tests). We also include a chapter on the important concept that association is not causation (@sec-association-not-causation), with a detailed discussion and examples of the challenges that arise when interpreting relationships between variables.

